/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Interfaces.CELL_TYPE;
import Interfaces.WORLD_TYPE;
import ToolClass.Parameter;

import javax.swing.JFrame;

/**
 *
 * @author chaki
 */
public class ParameterFrame extends JFrame {

    private WORLD_TYPE world = null ;
    private CELL_TYPE cell = null;
    
    /**
     * Creates new form ParameterFrame
     */
    public ParameterFrame() {
        initComponents();
        this.dispose();
        this.setUndecorated(true);
        this.setLocationRelativeTo(null);
        this.worldGroupe.setSelected(this.squareWorld.getModel(),true);
        this.cellsGroupe.setSelected(this.squareCell.getModel(),true);
        this.world =WORLD_TYPE.SQUARE;
        this.cell=CELL_TYPE.SQUARE;
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        worldGroupe = new javax.swing.ButtonGroup();
        cellsGroupe = new javax.swing.ButtonGroup();
        contentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        threshhold = new javax.swing.JSpinner();
        height = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        width = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        speedSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        squareSize = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        squareCell = new javax.swing.JRadioButton();
        hexagoanlCell = new javax.swing.JRadioButton();
        triangleCell = new javax.swing.JRadioButton();
        triangleWorld = new javax.swing.JRadioButton();
        squareWorld = new javax.swing.JRadioButton();
        hexaWorld = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        refreshRate = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        validBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parameters");
        setBackground(new java.awt.Color(246, 130, 13));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 380));

        contentPanel.setBackground(new java.awt.Color(246, 130, 13));

        jPanel1.setBackground(new java.awt.Color(255, 203, 43));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Threashhold");

        threshhold.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        threshhold.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.3f), Float.valueOf(0.3f), Float.valueOf(1.0f), Float.valueOf(0.1f)));

        height.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        height.setModel(new javax.swing.SpinnerNumberModel(500, 500, 500, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Height");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Width");

        width.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        width.setModel(new javax.swing.SpinnerNumberModel(650, 650, 650, 20));
        width.setAutoscrolls(true);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        speedSlider.setBackground(new java.awt.Color(255, 203, 43));
        speedSlider.setMaximum(2000);
        speedSlider.setMinimum(100);
        speedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                speedSliderStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Refresh rate");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Square size");

        squareSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        squareSize.setModel(new javax.swing.SpinnerNumberModel(10, 10, 150, 5));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cells type");

        squareCell.setBackground(new java.awt.Color(255, 203, 43));
        cellsGroupe.add(squareCell);
        squareCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        squareCell.setText("Square");
        squareCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareCellActionPerformed(evt);
            }
        });

        hexagoanlCell.setBackground(new java.awt.Color(255, 203, 43));
        cellsGroupe.add(hexagoanlCell);
        hexagoanlCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hexagoanlCell.setText("Hexagonal");
        hexagoanlCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexagoanlCellActionPerformed(evt);
            }
        });

        triangleCell.setBackground(new java.awt.Color(255, 203, 43));
        cellsGroupe.add(triangleCell);
        triangleCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        triangleCell.setText("Triangle");
        triangleCell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleCellActionPerformed(evt);
            }
        });

        triangleWorld.setBackground(new java.awt.Color(255, 203, 43));
        worldGroupe.add(triangleWorld);
        triangleWorld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        triangleWorld.setText("Triangle");
        triangleWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleWorldActionPerformed(evt);
            }
        });

        squareWorld.setBackground(new java.awt.Color(255, 203, 43));
        worldGroupe.add(squareWorld);
        squareWorld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        squareWorld.setText("Square");
        squareWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareWorldActionPerformed(evt);
            }
        });

        hexaWorld.setBackground(new java.awt.Color(255, 203, 43));
        worldGroupe.add(hexaWorld);
        hexaWorld.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hexaWorld.setText("Hexagonal");
        hexaWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexaWorldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("World type");

        refreshRate.setText("100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threshhold, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(squareSize, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triangleWorld, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(squareWorld, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hexaWorld, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshRate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(triangleCell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hexagoanlCell, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(squareCell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(threshhold, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(squareSize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(speedSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refreshRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(squareCell)
                                        .addGap(10, 10, 10)
                                        .addComponent(hexagoanlCell)
                                        .addGap(4, 4, 4)
                                        .addComponent(triangleCell))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hexaWorld)
                                        .addGap(10, 10, 10)
                                        .addComponent(squareWorld)
                                        .addGap(4, 4, 4)
                                        .addComponent(triangleWorld)))))
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );

        exit.setBackground(new java.awt.Color(5, 155, 229));
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Load Patch");

        validBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        validBtn.setText("valide");
        validBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(validBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void validBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validBtnActionPerformed
       int speed = speedSlider.getValue();
       int width = (int) this.width.getValue();
       int height = (int) this.height.getValue();
       float threshold =(float) this.threshhold.getValue();

       Parameter p = new Parameter(world, cell, speed, width, height, threshold);

       new MyAppFrame("Game of Life",p,this).setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_validBtnActionPerformed

    private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_speedSliderStateChanged
        this.refreshRate.setText(String.valueOf(this.speedSlider.getValue()));
    }//GEN-LAST:event_speedSliderStateChanged

    private void squareWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareWorldActionPerformed
        this.world= WORLD_TYPE.SQUARE;
    }//GEN-LAST:event_squareWorldActionPerformed

    private void hexaWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexaWorldActionPerformed
      this.world = WORLD_TYPE.HEXAGONAL;
    }//GEN-LAST:event_hexaWorldActionPerformed

    private void triangleWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleWorldActionPerformed
        this.world = WORLD_TYPE.TRIANGLE;
    }//GEN-LAST:event_triangleWorldActionPerformed

    private void squareCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareCellActionPerformed
       this.cell= CELL_TYPE.SQUARE;
    }//GEN-LAST:event_squareCellActionPerformed

    private void hexagoanlCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexagoanlCellActionPerformed
       this.cell=CELL_TYPE.HEXAGONAL;
    }//GEN-LAST:event_hexagoanlCellActionPerformed

    private void triangleCellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleCellActionPerformed
       this.cell = CELL_TYPE.TRIANGLE;
    }//GEN-LAST:event_triangleCellActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup cellsGroupe;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton exit;
    private javax.swing.JSpinner height;
    private javax.swing.JRadioButton hexaWorld;
    private javax.swing.JRadioButton hexagoanlCell;
    private javax.swing.JButton validBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel refreshRate;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JRadioButton squareCell;
    private javax.swing.JSpinner squareSize;
    private javax.swing.JRadioButton squareWorld;
    private javax.swing.JSpinner threshhold;
    private javax.swing.JRadioButton triangleCell;
    private javax.swing.JRadioButton triangleWorld;
    private javax.swing.JSpinner width;
    private javax.swing.ButtonGroup worldGroupe;
    // End of variables declaration//GEN-END:variables
}
